version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: onelast-ai-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: onelast-ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - onelast-ai-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onelast-ai-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/onelast-ai?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRE: 7d
      FRONTEND_URL: https://onelastai.com
      CORS_ORIGIN: https://onelastai.com,https://api.onelastai.com,https://agentx.onelastai.com,https://emo.onelastai.com,https://pdfmind.onelastai.com,https://astrology.onelastai.com
    depends_on:
      - mongodb
    networks:
      - onelast-ai-network
    volumes:
      - ./backend/logs:/app/logs

  # Main Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onelast-ai-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.onelastai.com
      NEXT_PUBLIC_WS_URL: wss://ws.onelastai.com
    networks:
      - onelast-ai-network

  # AgentX Subdomain
  agentx:
    build:
      context: ./subdomains/agentx
      dockerfile: Dockerfile
    container_name: onelast-ai-agentx
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.onelastai.com
    networks:
      - onelast-ai-network

  # EMO AI Subdomain
  emo:
    build:
      context: ./subdomains/emo
      dockerfile: Dockerfile
    container_name: onelast-ai-emo
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.onelastai.com
    networks:
      - onelast-ai-network

  # PDFMind Subdomain
  pdfmind:
    build:
      context: ./subdomains/pdfmind
      dockerfile: Dockerfile
    container_name: onelast-ai-pdfmind
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.onelastai.com
    networks:
      - onelast-ai-network

  # Astrology Subdomain
  astrology:
    build:
      context: ./subdomains/astrology
      dockerfile: Dockerfile
    container_name: onelast-ai-astrology
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.onelastai.com
    networks:
      - onelast-ai-network

  # Payment Validation Service
  payment-validation:
    build:
      context: ./payment_validation
      dockerfile: Dockerfile
    container_name: onelast-ai-payment-validation
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      API_URL: https://api.onelastai.com
    networks:
      - onelast-ai-network
    volumes:
      - ./payment_validation/logs:/app/logs

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: onelast-ai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - onelast-ai-network

volumes:
  mongodb_data:
  redis_data:

networks:
  onelast-ai-network:
    driver: bridge
